# Generated by Django 5.1.7 on 2025-08-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchapterprogress',
            name='highlight_color',
            field=models.CharField(choices=[('#baadec', 'Purple'), ('#b0e0eb', 'Blue'), ('#cbecaf', 'Green'), ('#ffffff', 'White')], default='#D2E8FF', max_length=7),
        ),
    ]
