# Generated by Django 5.2.5 on 2025-09-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userchapterprogress_highlight_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchapterprogress',
            name='advance_archive_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userchapterprogress',
            name='class_notes_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userchapterprogress',
            name='mains_archive_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userchapterprogress',
            name='ncert_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userchapterprogress',
            name='package_cpp_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userchapterprogress',
            name='package_section1_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userchapterprogress',
            name='package_section2_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userchapterprogress',
            name='package_section3_done',
            field=models.BooleanField(default=False),
        ),
    ]
