# Generated by Django 5.2.5 on 2025-09-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userchapterprogress_advance_archive_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchapterprogress',
            name='highlight_color',
            field=models.CharField(choices=[('#baadec', 'Purple'), ('#b0e0eb', 'Blue'), ('#cbecaf', 'Green'), ('#ffffff', 'White')], default='#ffffff', max_length=7),
        ),
    ]
