# Generated by Django 5.2.5 on 2025-09-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userchapterprogress_highlight_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchapterprogress',
            name='tab_assignments_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='subject',
            field=models.CharField(choices=[('phy', 'Physics'), ('chem', 'Chemistry'), ('math', 'Math')], max_length=10),
        ),
    ]
